# Generated by Django 5.2.4 on 2025-07-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autor', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado')], default='disponible', max_length=20)),
            ],
        ),
    ]
